##
# agent configuration
##
agent-host = "[::]"
agent-port = 8081

##
# api configuration
##
api-host = "[::]"
api-port = 8080

##
# ssl configuration
##
# cert-file = "/path/to/ssl/cert.pem"
# key-file = "/path/to/ssl/key.pem"
# trusted-ca-file = "/path/to/trusted-certificate-authorities.pem"
# insecure-skip-tls-verify = false

##
# store configuration
##
listen-client-urls = ""
listen-peer-urls = ""
initial-cluster = ""
initial-advertise-peer-urls = ""
initial-cluster-state = ""
initial-cluster-token = ""
name = ""

##
# dashboard configuration
##
dashboard-host = "[::]"
dashboard-port = 3000

##
# other
##
debug = false
deregistration-handler = ""
log-level = "warn"
